{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "3e48b47c_538e556b",
        "filename": "src/os/os_test.go",
        "patchSetId": 1
      },
      "lineNbr": 319,
      "author": {
        "id": 5206
      },
      "writtenOn": "2022-09-07T01:19:52Z",
      "side": 1,
      "message": "In the !ok case seems like this still uses \"e\" after a failed type assertion.",
      "revId": "13f651fff09a9ee8ac84592afcfc6bf00eedd896",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "cfc2d9fe_0d3a3014",
        "filename": "src/os/os_test.go",
        "patchSetId": 1
      },
      "lineNbr": 319,
      "author": {
        "id": 5206
      },
      "writtenOn": "2022-09-07T01:20:45Z",
      "side": 1,
      "message": "Ah, never mind, I see.",
      "parentUuid": "3e48b47c_538e556b",
      "revId": "13f651fff09a9ee8ac84592afcfc6bf00eedd896",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    }
  ]
}