{
  "comments": [
    {
      "key": {
        "uuid": "9f266a9b_691d2179",
        "filename": "src/encoding/json/encode.go",
        "patchSetId": 1
      },
      "lineNbr": 454,
      "author": {
        "id": 10570
      },
      "writtenOn": "2015-10-14T23:05:13Z",
      "side": 1,
      "message": "Is this equivalent/safe to call in all cases after e.error, if m.MarshalText returns err?\n\n(Same comment below)",
      "revId": "6583f9ff09e7fa9402d4958f16b9f49bc6cce382",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "df39c202_db3e44f4",
        "filename": "src/encoding/json/encode.go",
        "patchSetId": 1
      },
      "lineNbr": 454,
      "author": {
        "id": 7877
      },
      "writtenOn": "2015-10-14T23:11:23Z",
      "side": 1,
      "message": "e.error unconditionally panics. Other usages of e.error rely on this behavior too",
      "parentUuid": "9f266a9b_691d2179",
      "revId": "6583f9ff09e7fa9402d4958f16b9f49bc6cce382",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705",
      "unresolved": false
    }
  ]
}