{
  "comments": [
    {
      "key": {
        "uuid": "fba69f26_d477b21c",
        "filename": "src/net/mail/message_test.go",
        "patchSetId": 4
      },
      "lineNbr": 615,
      "author": {
        "id": 5065
      },
      "writtenOn": "2015-12-02T17:37:28Z",
      "side": 1,
      "message": "these don\u0027t fail with enough information to debug which test case failed.\n\nplease include the test index in the error message for both this line and line 618 and line 611 in a follow-up CL.",
      "revId": "ae86c03bce9b4fc0689fe7281a55a27b16142ca3",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705",
      "unresolved": false
    }
  ]
}