{
  "comments": [
    {
      "key": {
        "uuid": "1acae12f_0b3b9d7d",
        "filename": "src/cmd/go/internal/lockedfile/lockedfile_filelock.go",
        "patchSetId": 3
      },
      "lineNbr": 38,
      "author": {
        "id": 6365
      },
      "writtenOn": "2018-12-05T15:26:57Z",
      "side": 1,
      "message": "I think this can be a `:\u003d` now.\n\nAny idea what\u0027s up with the TryBot failure?",
      "range": {
        "startLine": 38,
        "startChar": 9,
        "endLine": 38,
        "endChar": 10
      },
      "revId": "bfec2f482b49549dde1f646dd49db3f4429c4302",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705",
      "unresolved": true
    }
  ]
}