{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "81e2595f_aea156f9",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 6365
      },
      "writtenOn": "2024-02-01T15:51:16Z",
      "side": 1,
      "message": "TryBot failure is unrelated (#65416).",
      "revId": "eaf2b64df63cb730d23009ed440a503060a763c4",
      "serverId": "62eb7196-b449-3ce5-99f1-c037f21e1705"
    }
  ]
}